---
name: "Frenck's Home Assistant Add-on Information"
description: >-
  🚀 Frenck's GitHub Action for gathering information from an Home Assistant
  Add-on.
author: frenck
branding:
  color: red
  icon: thumbs-up

inputs:
  path:
    description: Path to the add-on configuration (where config.json is)
    required: false
outputs:
  aarch64:
    description: Returns if the add-on supports the aarch64 architecture
    value: ${{ steps.architectures.outputs.aarch64 }}
  amd64:
    description: Returns if the add-on supports the amd64 architecture
    value: ${{ steps.architectures.outputs.amd64 }}
  architectures:
    description: Returns the list of supported architectures by this add-on
    value: ${{ steps.architectures.outputs.architectures }}
  armhf:
    description: Returns if the add-on supports the armhf architecture
    value: ${{ steps.architectures.outputs.armhf }}
  build:
    description: File location of the build.json configuration file
    value: ${{ steps.find.outputs.build }}
  config:
    description: File location of the add-on config.json configuration
    value: ${{ steps.find.outputs.config }}
  description:
    description: Description of the add-on
    value: ${{ steps.basic.outputs.description }}
  i386:
    description: Returns if the add-on supports the i386 architecture
    value: ${{ steps.architectures.outputs.i386 }}
  name:
    description: Return the name of the add-on
    value: ${{ steps.basic.outputs.name }}
  slug:
    description: Returns if the configured add-on slug
    value: ${{ steps.basic.outputs.slug }}
  target:
    description: Returns the add-on target folder name
    value: ${{ steps.find.outputs.target }}
  image:
    description: Image-template of the add-on
    value: ${{ steps.basic.outputs.image }}
  version:
    description: Returns the version of the add-on
    value: ${{ steps.basic.outputs.version }}
  armv7:
    description: Returns if the add-on supports the armv7 architecture
    value: ${{ steps.architectures.outputs.armv7 }}

runs:
  using: "composite"
  steps:
    - name: 🕵️ Find the add-on
      shell: bash
      id: find
      run: |
        if [[ -n "${{ inputs.path }}" ]]; then
          path="${{ inputs.path }}"
          path="${path%/}"

          for config_ext in json yaml yml; do
            if [[ -f "${path}/config.${config_ext}" ]]; then
              config="${path}/config.${config_ext}"
            fi
          done 

          if [[ -z "${config+x}" ]]; then
            echo "::error ::Could not find add-on configuration file in ${path}"
            exit 1
          fi
        else
          if ! find \
            ./ -mindepth 2 -maxdepth 2 \
            -regex ".*\config\.\(json\|yaml\|yml\)$" \
            | head -1 | grep --silent .;
          then
            echo "::error ::Could not find add-on configuration file"
            exit 1
          fi

          config=$(
            find ./ -mindepth 2 -maxdepth 2 \
            -regex ".*\config\.\(json\|yaml\|yml\)$" -printf '%P\n' \
            | head -1
          )
        fi

        echo "::set-output name=config::${config}"

        target=$(dirname "${config}")
        echo "::set-output name=target::${target}"

        for config_ext in json yaml yml; do
          if [[ -f "${target}/build.${config_ext}" ]]; then
            build="${target}/build.${config_ext}"
          fi
        done

        if [[ -z "${build+x}" ]]; then
          echo "::error ::Could not find add-on build file"
          exit 1
        fi
        echo "::set-output name=build::${build}"
    - name: ℹ️ Extract basic add-on information
      shell: bash
      id: basic
      run: |
        slug=$(yq --no-colors eval '.slug' "${{ steps.find.outputs.config }}")
        echo "::set-output name=slug::${slug}"

        name=$(yq --no-colors eval '.name' "${{ steps.find.outputs.config }}")
        echo "::set-output name=name::${name}"

        description=$(yq --no-colors eval '.description' "${{ steps.find.outputs.config }}")
        echo "::set-output name=description::${description}"

        image=$(yq --no-colors eval '.image // empty' "${{ steps.find.outputs.config }}")
        echo "::set-output name=image::${image}"

        version=$(yq --no-colors eval '.version' "${{ steps.find.outputs.config }}")
        echo "::set-output name=version::${version}"

    - name: ℹ️ Extract add-on architecture information
      shell: bash
      id: architectures
      run: |
        architectures=$(
          yq --no-colors eval '.arch' "${{ steps.find.outputs.config }}" \
            | jq --raw-output --compact-output '. | sort'
        )
        echo "::set-output name=architectures::${architectures}"

        for architecture in \
          aarch64 \
          amd64 \
          armhf \
          armv7 \
          i386;
        do
          available=$(
            yq --no-colors yq --no-colors eval ".arch[] \
              | select(. == \"${architecture}\") | . or false" "${{ steps.find.outputs.config }}"
          )
          echo "::set-output name=${architecture}::${available}"
        done
